version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: shifts-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - shifts-network
    depends_on:
      - app

  app:
    build:
      args:
        user: root
        uid: 1000
      context: ./.docker/app
      dockerfile: Dockerfile
    image: shifts
    container_name: shifts
    restart: unless-stopped
    ports:
      - 6001:6001
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/app/php-fpm.ini:/usr/local/etc/php/conf.d/99-app.ini
    networks:
      - shifts-network
    depends_on:
      - database

  database:
    image: mariadb:10.5.8
    container_name: shifts-mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - shifts-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: shifts
      MYSQL_TCP_PORT: 3306
    networks:
      - shifts-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shifts-phpmyadmin
    restart: unless-stopped
    tty: true
    depends_on:
      - database
    ports:
      - 8088:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 300M
    networks:
      - shifts-network

  mailhog:
    image: 'mailhog/mailhog'
    container_name: shifts-mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - shifts-network

networks:
  shifts-network:
    driver: bridge

volumes:
  shifts-volume:
    driver: local
